language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - chmod +x mvnw
  - ./mvnw clean test
  - ./mvnw verify -Pprod -DskipTests
os: linux
  dist: trusty
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: desafioapi-travis
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false